### ISSUE TITLE
Deprecated dependency "sklearn"

### ISSUE THREAD

**Issue by nathan-moore-97** [wdbm/scalar#1]
`sklearn` is deprecated, replaced with `scikit-learn`.

**Comment by wdbm** [comment]
Thanks for the alert. In fact, this project does not import Scikit-learn directly. However, it does import a package which imports a package which imports Scikit-learn. Respectfully, in reporting items like this in future, please don't expect developers to work for free by investigating matters like this. It is better for you to identify the package which is actually importing the problem package directly, and then raising the issue in the appropriate place.
